FROM node:10-stretch

WORKDIR /var/www/client

ADD package.json ./
#COPY package.json ./
COPY angular.json ./
COPY tsconfig.json ./
RUN npm install -g typescript nodemon @angular/cli@latest
RUN npm install -g node-sass@latest --unsafe-perm=true --allow-root
RUN npm install -g fullcalendar
RUN npm install
CMD ng serve --host 0.0.0.0 --port 80 --poll 1
